### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by ansharlubis** [prg-titech/pbatakjava#14]
### Base work

**CONSTRAINT**

- [x] Method call's arguments #16 
- [x] Types assigned with the same parameters are consistent #20 
  - Class instance with variable arguments `new C#V#()`
  - Method call with variable arguments `«V»m()`
- [x] Return statement  #20 
- [x] Implement subtyping #24
- [x] Constraint on numbered `VersionTypeAccess` #31 

**COMPILATION**

- [x] Method declarations with version variables #15
- [x] Method call with version arguments #15
- [x] `new C#V#()` #17 
- [x] `«V»m()` #17 
- [x] Polymorphic calling monomorpic (refer: #30)
- [x] Different versions with different constructors #28 
  - [x] More examples on this

**CHECK**

- [x] Version number arguments satisfy the set of solutions #19 
- [x] Number of version arguments (instances, method calls) #16 

**TEST**

- [x] Make reference tests #25

**Comment by ansharlubis** [comment]
### Further work

- [ ] Different versions with different constructors
